-- AlterEnum: expand ProviderType for additional job sources
ALTER TYPE "ProviderType" ADD VALUE IF NOT EXISTS 'REMOTIVE';
ALTER TYPE "ProviderType" ADD VALUE IF NOT EXISTS 'JOBICY';
ALTER TYPE "ProviderType" ADD VALUE IF NOT EXISTS 'HIMALAYAS';
ALTER TYPE "ProviderType" ADD VALUE IF NOT EXISTS 'REMOTEOK';
ALTER TYPE "ProviderType" ADD VALUE IF NOT EXISTS 'REMOTEJOBS_ORG';
ALTER TYPE "ProviderType" ADD VALUE IF NOT EXISTS 'ASHBY';
ALTER TYPE "ProviderType" ADD VALUE IF NOT EXISTS 'RECRUITEE';
ALTER TYPE "ProviderType" ADD VALUE IF NOT EXISTS 'PERSONIO';
