import { AppError } from '@/shared/utils/errors/AppError.js';

export const RECOMMENDATION_ERROR_CODES = {
  SOURCE_NOT_SUPPORTED: 'RECOMMENDATION_SOURCE_NOT_SUPPORTED',
  SOURCE_NOT_FOUND: 'RECOMMENDATION_SOURCE_NOT_FOUND',
  CONTEXT_INVALID: 'RECOMMENDATION_CONTEXT_INVALID',
  RUN_NOT_FOUND: 'RECOMMENDATION_RUN_NOT_FOUND',
  RECOMMENDATION_NOT_FOUND: 'RECOMMENDATION_NOT_FOUND',
  ACCESS_DENIED: 'RECOMMENDATION_ACCESS_DENIED',
  TARGET_TEXT_REQUIRED: 'TARGET_TEXT_REQUIRED',
  TARGET_TEXT_TOO_LONG: 'TARGET_TEXT_TOO_LONG',
  NO_ELIGIBLE_JOBS_FOUND: 'NO_ELIGIBLE_JOBS_FOUND',
  EMBEDDING_PROVIDER_UNAVAILABLE: 'EMBEDDING_PROVIDER_UNAVAILABLE',
  GENERATION_FAILED: 'RECOMMENDATION_GENERATION_FAILED',
  NOT_IMPLEMENTED: 'JOB_RECOMMENDATIONS_NOT_IMPLEMENTED',
  SCORING_NOT_CONFIGURED: 'JOB_RECOMMENDATIONS_SCORING_NOT_CONFIGURED',
} as const;

export class RecommendationError extends AppError {
  constructor(
    message: string,
    statusCode: number,
    code: (typeof RECOMMENDATION_ERROR_CODES)[keyof typeof RECOMMENDATION_ERROR_CODES],
  ) {
    super(message, statusCode, code);
    this.name = 'RecommendationError';
  }
}
