import type { ElementType } from 'react';

import { Box, styled } from '@/lib/material';

import {
  border,
  borderRadius,
  colorTokens,
  fontSize,
  fontWeight,
  iconBox,
  muted,
  panel,
  pill,
  spacing,
  t,
  title,
  tone,
  type ToneName,
} from '../../styles/shared';

export { CardSubtitle, CardTitle, EmptyText, FileTile } from '../../styles/shared';

export const Panel = styled(Box)({
  ...panel,
  gap: spacing[5],
  margin: spacing[8],
  padding: spacing[8],
});

export const OptimizeStatus = styled(Box, {
  shouldForwardProp: (prop) => prop !== 'variant',
})<{ variant: 'good' | 'warn' | 'medium' | 'impact' }>(({ variant }) => {
  const c = variant === 'good' ? tone.success : variant === 'impact' ? tone.error : tone.warning;
  return {
    ...pill,
    background: c.background,
    border: `1px solid ${c.border}`,
    color: c.color,
    fontStyle: 'normal',
    justifySelf: 'start',
  };
});

export const ToneIconBox = styled(Box, {
  shouldForwardProp: (prop) => prop !== 'tone',
})<{ tone: ToneName }>(({ tone: name }) => ({
  ...iconBox('2.25rem'),
  background: tone[name].background,
  borderRadius: borderRadius.lg,
  color: tone[name].color,
}));

export const ToneCountBadge = styled(Box, {
  shouldForwardProp: (prop) => prop !== 'tone',
})<{ tone: ToneName }>(({ tone: name }) => ({
  background: tone[name].background,
  borderRadius: borderRadius.lg,
  color: tone[name].color,
  fontSize: fontSize.sm,
  fontWeight: fontWeight.extraBold,
  lineHeight: 1,
  padding: '0.45rem 0.6rem',
}));

export const KeywordChip = styled(Box, {
  shouldForwardProp: (prop) => prop !== 'selected',
})<{ selected?: boolean; component?: ElementType }>(({ selected = false }) => ({
  alignItems: 'center',
  background: selected ? t.greenBadgeBg : t.redBadgeBg,
  border: `1px solid ${selected ? t.greenBadgeBorder : t.redBadgeBorder}`,
  borderRadius: borderRadius.lg,
  color: selected ? t.greenBadgeText : t.redBadgeText,
  cursor: 'pointer',
  display: 'inline-flex',
  fontFamily: 'inherit',
  fontSize: fontSize.xs,
  fontWeight: fontWeight.semiBold,
  gap: spacing[1],
  padding: `${spacing[2]} ${spacing[3]}`,
  transition: 'background 160ms ease, border-color 160ms ease, color 160ms ease',
  '& svg': { fontSize: '0.9rem' },
}));

export const AnalysisShell = styled(Box)({
  display: 'grid',
  gap: spacing[4],
  gridTemplateColumns: 'minmax(0, 1fr) 24rem',
  padding: `${spacing[4]} ${spacing[6]} ${spacing[6]}`,
  '@media (max-width: 76rem)': { gridTemplateColumns: '1fr' },

  '& .aside': { alignSelf: 'start', display: 'grid', gap: spacing[4] },
  '& .aside-card': { ...panel, background: 'rgba(255,255,255,0.96)' },
  '& .aside-title': { ...title, fontSize: fontSize.base },
  '& .aside-title-row': {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
  },
  '& .uploaded-resume': {
    alignItems: 'center',
    background: `linear-gradient(135deg, ${t.background}, ${t.primarySofter})`,
    border: '1px solid rgba(37, 99, 235, 0.16)',
    borderRadius: borderRadius.xl,
    display: 'grid',
    gap: spacing[3],
    gridTemplateColumns: '3.25rem minmax(0, 1fr)',
    padding: spacing[3],
  },
  '& .resume-name': {
    color: t.text,
    fontWeight: fontWeight.extraBold,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  '& .resume-subtext': { ...muted, fontSize: fontSize.xs },
  '& .next-item': { alignItems: 'center', display: 'flex', gap: spacing[3] },
  '& .next-icon': iconBox(),
  '& .next-text': { color: t.text, fontSize: fontSize.sm, fontWeight: fontWeight.semiBold },
  '& .step-title': {
    ...title,
    fontSize: fontSize['2xl'],
    lineHeight: 1.2,
    '& span': { color: t.primary },
  },
  '& .tip-title': {
    color: t.primaryHover,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.extraBold,
  },
  '& .tip-text': { ...muted, fontSize: fontSize.xs, lineHeight: 1.55 },
});

export const AnalysisMain = styled(Box, {
  shouldForwardProp: (prop) => prop !== 'loading',
})<{ loading?: boolean }>(({ loading = false }) => ({
  ...panel,
  background: 'rgba(255,255,255,0.98)',
  gap: spacing[4],
  minWidth: 0,
  overflow: 'hidden',
  padding: spacing[5],
  position: 'relative',
  '& > *:not(.analysis-loading-glow)': {
    opacity: loading ? 0.74 : 1,
    transition: 'opacity 180ms ease',
  },

  '& .heading': {
    alignItems: 'start',
    display: 'flex',
    gap: spacing[4],
    justifyContent: 'space-between',
    '@media (max-width: 48rem)': { flexDirection: 'column' },
  },
  '& .score-card': {
    border,
    borderRadius: borderRadius.xl,
    display: 'grid',
    gap: spacing[5],
    gridTemplateColumns: '16rem minmax(0, 1fr)',
    overflow: 'hidden',
    padding: spacing[5],
    position: 'relative',
    '@media (max-width: 56rem)': { gridTemplateColumns: '1fr' },
  },
  '& .score-block': {
    borderRight: border,
    display: 'grid',
    gap: spacing[4],
    justifyItems: 'center',
    paddingRight: spacing[6],
    '@media (max-width: 56rem)': {
      borderBottom: border,
      borderRight: 0,
      paddingBottom: spacing[5],
      paddingRight: 0,
    },
  },
  '& .card-title': { ...title, fontSize: fontSize.sm },
  '& .score-ring': { display: 'inline-flex', position: 'relative' },
  '& .score-value': {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'column',
    inset: 0,
    justifyContent: 'center',
    position: 'absolute',
  },
  '& .score-number': {
    ...title,
    fontSize: fontSize['3xl'],
    lineHeight: 1,
    '& span': { ...muted, fontSize: fontSize.base, fontWeight: fontWeight.medium },
  },
  '& .score-label': {
    color: t.greenBadgeText,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    marginTop: spacing[2],
  },
  '& .score-summary': { alignContent: 'center', display: 'grid', gap: '1.75rem' },
  '& .score-topline': {
    alignItems: 'start',
    display: 'flex',
    gap: spacing[4],
    justifyContent: 'space-between',
    '@media (max-width: 48rem)': { flexDirection: 'column' },
  },
  '& .summary-title': { ...title, fontSize: fontSize.base },
  '& .range': { display: 'grid', gap: spacing[3] },
  '& .range-bar': {
    background: 'linear-gradient(90deg, #FF5A61 0 35%, #F6AD3D 35% 67%, #58C98C 67% 100%)',
    borderRadius: borderRadius.full,
    height: '0.5rem',
    position: 'relative',
  },
  '& .range-numbers': {
    ...muted,
    display: 'flex',
    fontSize: fontSize.xs,
    justifyContent: 'space-between',
  },
  '& .legend': {
    display: 'grid',
    gap: spacing[4],
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    '& div': { color: t.text, fontSize: fontSize.xs, fontWeight: fontWeight.semiBold },
    '& small': { color: t.textSecondary, fontWeight: fontWeight.medium },
    '& span': {
      borderRadius: borderRadius.full,
      display: 'inline-block',
      height: '0.6rem',
      marginRight: spacing[2],
      width: '0.6rem',
    },
    '& .needs': { background: '#FF5A61' },
    '& .good': { background: '#F6AD3D' },
    '& .excellent': { background: '#58C98C' },
  },
  '& .metrics-grid': {
    display: 'grid',
    gap: spacing[3],
    gridTemplateColumns: 'repeat(5, minmax(0, 1fr))',
    '@media (max-width: 64rem)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
    '@media (max-width: 40rem)': { gridTemplateColumns: '1fr' },
  },
  '& .metric-card': {
    border,
    borderRadius: borderRadius.xl,
    display: 'grid',
    gap: spacing[2],
    padding: spacing[3],
  },
  '& .metric-label': { ...muted, fontSize: fontSize.xs },
  '& .metric-value': { ...title, fontSize: fontSize.xl, lineHeight: 1 },
  '& .metric-track': {
    background: t.primarySofter,
    borderRadius: borderRadius.full,
    height: '0.4rem',
    overflow: 'hidden',
  },
  '& .metric-fill': {
    background: t.primary,
    borderRadius: borderRadius.full,
    height: '100%',
  },
  '& .detail-grid': {
    display: 'grid',
    gap: spacing[4],
    gridTemplateColumns: '1.1fr 0.9fr',
    '@media (max-width: 64rem)': { gridTemplateColumns: '1fr' },
  },
  '& .section-scores': { display: 'grid', gap: spacing[3] },
  '& .section-row': {
    alignItems: 'center',
    display: 'grid',
    gap: spacing[3],
    gridTemplateColumns: '7rem minmax(0, 1fr) 2.5rem',
  },
  '& .section-name': {
    color: t.text,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semiBold,
    textTransform: 'capitalize',
  },
  '& .section-value': {
    color: t.textSecondary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    textAlign: 'right',
  },
  '& .skill-columns': {
    display: 'grid',
    gap: spacing[3],
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    '@media (max-width: 48rem)': { gridTemplateColumns: '1fr' },
  },
  '& .skill-group': { display: 'grid', gap: spacing[2] },
  '& .skill-group-title': {
    color: t.textSecondary,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.extraBold,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
  '& .issue-list': { display: 'grid', gap: spacing[3] },
  '& .issue-item': {
    border,
    borderRadius: borderRadius.lg,
    display: 'grid',
    gap: spacing[1],
    padding: spacing[3],
  },
  '& .issue-top': {
    alignItems: 'center',
    display: 'flex',
    gap: spacing[2],
    justifyContent: 'space-between',
  },
  '& .issue-title': {
    color: t.text,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semiBold,
  },
  '& .issue-fix': { ...muted, fontSize: fontSize.xs },
  '& .severity': {
    ...pill,
    fontSize: '0.65rem',
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
  '& .severity-high': {
    background: tone.error.background,
    border: `1px solid ${tone.error.border}`,
    color: tone.error.color,
  },
  '& .severity-medium': {
    background: tone.warning.background,
    border: `1px solid ${tone.warning.border}`,
    color: tone.warning.color,
  },
  '& .severity-low': {
    background: tone.success.background,
    border: `1px solid ${tone.success.border}`,
    color: tone.success.color,
  },
  '& .insight-grid': {
    display: 'grid',
    gap: spacing[4],
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    '@media (max-width: 64rem)': { gridTemplateColumns: '1fr' },
  },
  '& .insight-card': {
    alignContent: 'start',
    border,
    borderRadius: borderRadius['2xl'],
    display: 'grid',
    gap: spacing[3],
    minHeight: '13rem',
    minWidth: 0,
    overflow: 'hidden',
    padding: spacing[4],
  },
  '& .insight-header': {
    alignItems: 'center',
    display: 'grid',
    gap: spacing[3],
    gridTemplateColumns: 'auto minmax(0, 1fr) auto',
  },
  '& .keyword-wrap': { display: 'flex', flexWrap: 'wrap', gap: spacing[2] },
  '& .bullet-list': { display: 'grid', gap: spacing[2] },
  '& .bullet': {
    alignItems: 'flex-start',
    color: t.text,
    display: 'flex',
    fontSize: fontSize.sm,
    gap: spacing[2],
    lineHeight: 1.45,
    overflowWrap: 'anywhere',
    '& svg': { color: t.greenBadgeText, fontSize: '1rem' },
    '& .error': {
      ...iconBox('1rem'),
      background: 'transparent',
      border: `1px solid ${t.redBadgeText}`,
      borderRadius: borderRadius.full,
      color: t.redBadgeText,
      fontSize: '0.65rem',
    },
  },
  '& .progress-notice': {
    alignItems: 'center',
    background: `linear-gradient(135deg, ${t.primarySoft}, ${t.background})`,
    border: '1px solid rgba(37, 99, 235, 0.2)',
    borderRadius: borderRadius['2xl'],
    color: t.primary,
    display: 'grid',
    gap: spacing[4],
    gridTemplateColumns: 'auto minmax(0, 1fr) auto',
    padding: spacing[4],
    '@media (max-width: 56rem)': { gridTemplateColumns: 'auto minmax(0, 1fr)' },
  },
}));

export const AnalysisLoadingGlow = styled(Box)({
  '@keyframes analysisScan': {
    '0%': { transform: 'translateX(-120%)' },
    '100%': { transform: 'translateX(120%)' },
  },
  animation: 'analysisScan 1.8s ease-in-out infinite',
  background:
    'linear-gradient(90deg, transparent, rgba(37, 99, 235, 0.1), rgba(255,255,255,0.58), rgba(37, 99, 235, 0.08), transparent)',
  inset: 0,
  pointerEvents: 'none',
  position: 'absolute',
  transform: 'translateX(-120%)',
  zIndex: 1,
});

export const AnalysisScoreTrackSx = { color: t.primarySofter, position: 'absolute' as const };

export const analysisScoreProgressSx = (hasScore: boolean) => ({
  color: hasScore ? t.primary : '#60A5FA',
  filter: 'drop-shadow(0 10px 18px rgba(37, 99, 235, 0.22))',
  transform: 'rotate(-90deg)',
  '& .MuiCircularProgress-circle': { strokeLinecap: 'round' as const },
});

export const AnalysisRangeMarker = styled(Box, {
  shouldForwardProp: (prop) => prop !== 'score',
})<{ score: number }>(({ score }) => ({
  background: '#35C37D',
  border: '3px solid #FFFFFF',
  borderRadius: borderRadius.full,
  boxShadow: '0 8px 18px rgba(22,163,74,0.25)',
  height: '1.25rem',
  left: `${Math.min(100, Math.max(0, score))}%`,
  position: 'absolute',
  top: '50%',
  transform: 'translate(-50%, -50%)',
  width: '1.25rem',
}));

export const ReviewShell = styled(Box, {
  shouldForwardProp: (prop) => prop !== 'withPreview',
})<{ withPreview?: boolean }>(({ withPreview = false }) => ({
  display: 'grid',
  gap: spacing[4],
  gridTemplateColumns: withPreview ? 'minmax(0, 0.95fr) minmax(0, 1.05fr)' : 'minmax(0, 1fr)',
  padding: `${spacing[4]} ${spacing[6]} ${spacing[6]}`,
  '@media (max-width: 76rem)': { gridTemplateColumns: '1fr' },
}));

export const ReviewPanel = styled(Box)({
  ...panel,
  gap: spacing[4],
  padding: spacing[5],

  '& .header': { display: 'grid', gap: spacing[2] },
  '& .title': { ...title, fontSize: fontSize['2xl'], lineHeight: 1.2 },
  '& .score-strip': {
    alignItems: 'center',
    border,
    borderRadius: borderRadius.xl,
    display: 'grid',
    gap: spacing[5],
    gridTemplateColumns: '1fr auto 1fr auto',
    padding: spacing[4],
    '@media (max-width: 48rem)': { gridTemplateColumns: '1fr' },
  },
  '& .current-score': {
    color: '#E11D48',
    fontSize: fontSize['2xl'],
    fontWeight: fontWeight.extraBold,
  },
  '& .improved-score': {
    color: t.greenBadgeText,
    fontSize: fontSize['2xl'],
    fontWeight: fontWeight.extraBold,
  },
  '& .increase-badge': {
    ...pill,
    background: t.greenBadgeBg,
    border: `1px solid ${t.greenBadgeBorder}`,
    color: t.greenBadgeText,
    justifySelf: 'start',
  },
  '& .resume-subtext': { ...muted, fontSize: fontSize.xs },
  '& .editor-layout': {
    display: 'grid',
    gap: spacing[4],
    gridTemplateColumns: '17rem minmax(0, 1fr)',
    '@media (max-width: 64rem)': { gridTemplateColumns: '1fr' },
  },
  '& .section-nav': {
    border,
    borderRadius: borderRadius['2xl'],
    display: 'grid',
    gap: spacing[2],
    padding: spacing[4],
    '& button:not(.MuiButton-root)': {
      alignItems: 'center',
      background: t.background,
      border,
      borderRadius: borderRadius.lg,
      color: t.text,
      cursor: 'pointer',
      display: 'flex',
      fontFamily: 'inherit',
      fontSize: fontSize.sm,
      fontWeight: fontWeight.semiBold,
      gap: spacing[3],
      justifyContent: 'space-between',
      minHeight: '2.75rem',
      padding: `${spacing[2]} ${spacing[3]}`,
      textAlign: 'left',
    },
    '& button.active': {
      background: t.primarySofter,
      borderColor: 'rgba(37, 99, 235, 0.35)',
      color: t.primary,
    },
  },
  '& .nav-title': {
    color: t.primary,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.extraBold,
    textTransform: 'uppercase',
  },
  '& .edit-card': {
    border,
    borderRadius: borderRadius['2xl'],
    display: 'grid',
    gap: spacing[3],
    padding: spacing[4],
    '& textarea': { minHeight: '22rem', lineHeight: 1.7 },
  },
  '& .selected-header': {
    alignItems: 'start',
    borderBottom: border,
    display: 'flex',
    gap: spacing[4],
    justifyContent: 'space-between',
    paddingBottom: spacing[4],
    '& h2 span, & .MuiTypography-root span': {
      marginLeft: spacing[3],
      verticalAlign: 'middle',
    },
  },
  '& .compare-grid': {
    alignItems: 'center',
    display: 'grid',
    gap: spacing[5],
    gridTemplateColumns: 'minmax(0, 1fr) auto minmax(0, 1fr)',
    '@media (max-width: 64rem)': { gridTemplateColumns: '1fr' },
  },
  '& .editor-pane': {
    display: 'grid',
    gap: spacing[3],
    '& textarea': {
      borderColor: 'rgba(37, 99, 235, 0.5)',
      fontSize: fontSize.lg,
      lineHeight: 1.55,
      minHeight: '15rem',
      padding: spacing[5],
    },
  },
  '& .card-title': { ...title, fontSize: fontSize.sm },
  '& .arrow': {
    alignItems: 'center',
    color: t.primary,
    display: 'flex',
    fontSize: fontSize['3xl'],
    justifyContent: 'center',
    '& svg': { fontSize: '3rem' },
  },
  '& .suggested-pane': {
    background: t.greenBadgeBg,
    border: `1px solid ${t.greenBadgeBorder}`,
    borderRadius: borderRadius.xl,
    display: 'grid',
    gap: spacing[3],
    minHeight: '15rem',
    padding: spacing[5],
  },
  '& .tip-box': {
    alignItems: 'center',
    background: `linear-gradient(135deg, ${t.primarySoft}, ${t.background})`,
    borderRadius: borderRadius.lg,
    color: t.primary,
    display: 'flex',
    gap: spacing[2],
    padding: spacing[3],
  },
  '& .preview-header': {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
  },
  '& .preview-text': {
    color: t.text,
    fontSize: fontSize.sm,
    lineHeight: 1.7,
    whiteSpace: 'pre-wrap',
  },
  '& .ai-card': {
    alignItems: 'center',
    background: `linear-gradient(135deg, ${t.primarySoft}, ${t.background})`,
    border: '1px solid rgba(37, 99, 235, 0.2)',
    borderRadius: borderRadius['2xl'],
    display: 'grid',
    gap: spacing[4],
    gridTemplateColumns: 'auto minmax(0, 1fr) auto',
    padding: spacing[5],
    '@media (max-width: 48rem)': { gridTemplateColumns: 'auto minmax(0, 1fr)' },
  },
  '& .ai-icon': iconBox('3rem'),
  '& .tip-title': {
    color: t.primaryHover,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.extraBold,
  },
  '& .tip-text': { ...muted, fontSize: fontSize.xs, lineHeight: 1.55 },
  '& .issues-card': {
    border,
    borderRadius: borderRadius['2xl'],
    display: 'grid',
    gap: spacing[3],
    padding: spacing[4],
  },
  '& .template-grid': {
    display: 'grid',
    gap: spacing[4],
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    '@media (max-width: 48rem)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
    '& button': {
      alignItems: 'end',
      aspectRatio: '3 / 4',
      background: 'linear-gradient(160deg, #FFFFFF 0%, #FFFFFF 60%, #EFF6FF 60%, #EFF6FF 100%)',
      border,
      borderRadius: borderRadius.xl,
      color: t.text,
      cursor: 'pointer',
      display: 'flex',
      fontFamily: 'inherit',
      fontSize: fontSize.xs,
      fontWeight: fontWeight.extraBold,
      padding: spacing[3],
    },
    '& button.active': {
      borderColor: t.primary,
      boxShadow: t.purpleShadow,
      color: t.primary,
    },
  },
});

export const ReviewPreviewPanel = styled(Box)({
  ...panel,
  gap: spacing[4],
  padding: spacing[5],

  '& .preview-header': {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
  },
  '& .card-title': { ...title, fontSize: fontSize.sm },
  '& .resume-subtext': { ...muted, fontSize: fontSize.xs },
  '& .paper': {
    border,
    borderRadius: borderRadius['2xl'],
    color: t.text,
    display: 'grid',
    gap: spacing[4],
    maxHeight: '38rem',
    minHeight: '28rem',
    overflowY: 'auto',
    padding: spacing[8],
    scrollbarColor: `${t.textMuted} transparent`,
    scrollbarWidth: 'thin',
  },
  '& .preview-name': { ...title, fontSize: fontSize['3xl'], lineHeight: 1.1 },
  '& .preview-role': {
    color: t.primary,
    fontSize: fontSize.base,
    fontWeight: fontWeight.extraBold,
  },
  '& .contact-row': {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing[5],
    '& span': {
      alignItems: 'center',
      display: 'inline-flex',
      fontSize: fontSize.xs,
      gap: spacing[1],
    },
    '& svg': { fontSize: '0.95rem' },
  },
  '& .section': { display: 'grid', gap: spacing[2] },
  '& .section-title': {
    color: t.primary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.extraBold,
  },
  '& .preview-text': {
    color: t.text,
    fontSize: fontSize.sm,
    lineHeight: 1.7,
    whiteSpace: 'pre-wrap',
  },
  '& .job-header': {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
  },
  '& .job-title': { ...title, fontSize: fontSize.sm },
  '& .company': { color: t.primary, fontSize: fontSize.sm, fontWeight: fontWeight.semiBold },
  '& .skill-row': {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing[2],
    '& span': {
      background: t.primarySoft,
      borderRadius: borderRadius.full,
      color: t.primary,
      fontSize: fontSize.xs,
      fontWeight: fontWeight.medium,
      padding: `${spacing[1]} ${spacing[3]}`,
    },
  },
  '& .score-strip': {
    alignItems: 'center',
    border,
    borderRadius: borderRadius.xl,
    display: 'grid',
    gap: spacing[5],
    gridTemplateColumns: '1fr auto 1fr auto',
    padding: spacing[4],
    '@media (max-width: 48rem)': { gridTemplateColumns: '1fr' },
  },
  '& .current-score': {
    color: '#E11D48',
    fontSize: fontSize['2xl'],
    fontWeight: fontWeight.extraBold,
  },
  '& .improved-score': {
    color: t.greenBadgeText,
    fontSize: fontSize['2xl'],
    fontWeight: fontWeight.extraBold,
  },
});

export const VersionRow = styled(Box)({
  alignItems: 'center',
  background: colorTokens.backgroundApp,
  border,
  borderRadius: borderRadius.xl,
  display: 'flex',
  gap: spacing[3],
  justifyContent: 'space-between',
  padding: spacing[3],
});

export const ActionsRow = styled(Box)({
  display: 'flex',
  flexWrap: 'wrap',
  gap: spacing[3],
  justifyContent: 'flex-end',
});
