import { chatWithOpenRouter } from '@/modules/copilot/ai/openrouter-chat.js';
import type { OpenRouterConfig } from '@/modules/resumes/ai/providers/openrouter/openrouter.js';
import { resumeConfig } from '@/modules/resumes/config/resume.config.js';
import { assertSafeGeneratedText } from '@/modules/auto-apply/services/content-safety.util.js';
import { logger } from '@/shared/logger/logger.js';

export interface DraftAnswerGenerationInput {
  question: string;
  resumeText: string;
  candidateName?: string | null;
}

export interface IDraftAnswerGenerationPort {
  generate(input: DraftAnswerGenerationInput): Promise<string>;
}

const SYSTEM_PROMPT = `You write concise, professional answers to job application questions.
Rules (must follow):
- Use ONLY facts present in the provided resume text.
- Never invent employers, degrees, certifications, years of experience, skills, salary, or work authorization.
- Do not mention demographics, disability, veteran status, or other protected attributes.
- Keep the answer under 150 words.
- Output plain text only.`;

function buildUserPrompt(input: DraftAnswerGenerationInput): string {
  const nameLine = input.candidateName?.trim()
    ? `Candidate name: ${input.candidateName.trim()}`
    : 'Candidate name: (unknown)';

  return [
    nameLine,
    '',
    'RESUME (source of truth):',
    input.resumeText.slice(0, 12_000),
    '',
    `QUESTION TO ANSWER: ${input.question}`,
    '',
    'Write the answer now.',
  ].join('\n');
}

function resolveOpenRouterConfig(): OpenRouterConfig | null {
  const apiKey = resumeConfig.ai.openrouter.apiKey?.trim();
  if (!apiKey) return null;
  return {
    apiKey,
    model: resumeConfig.ai.openrouter.model,
    baseUrl: resumeConfig.ai.openrouter.baseUrl,
    temperature: 0.3,
    timeoutMs: resumeConfig.ai.openrouter.timeoutMs,
  };
}

export class OpenRouterDraftAnswerGenerator implements IDraftAnswerGenerationPort {
  async generate(input: DraftAnswerGenerationInput): Promise<string> {
    const config = resolveOpenRouterConfig();
    if (!config) {
      throw new Error('OpenRouter is not configured (OPENROUTER_API_KEY).');
    }

    const text = await chatWithOpenRouter(
      {
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: buildUserPrompt(input) },
        ],
        maxTokens: 300,
        temperature: 0.3,
      },
      config,
    );

    return assertSafeGeneratedText(text);
  }
}

/** Test double / offline fallback — template draft answer with no invented facts. */
export class TemplateDraftAnswerGenerator implements IDraftAnswerGenerationPort {
  async generate(input: DraftAnswerGenerationInput): Promise<string> {
    logger.info({ question: input.question }, 'Using template draft answer (no AI provider)');
    return `This is a drafted template answer for the question: "${input.question}". In production, this would be generated by AI based on your resume.`;
  }
}
