export enum ResumeParseStatus {
  QUEUED = 'QUEUED',
  EXTRACTING_TEXT = 'EXTRACTING_TEXT',
  CHECKING_EXTRACTION = 'CHECKING_EXTRACTION',
  PARSING = 'PARSING',
  VALIDATING = 'VALIDATING',
  NORMALISING = 'NORMALISING',
  COMPLETED = 'COMPLETED',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  FAILED = 'FAILED',
}
