export enum ResumeParserErrorCode {
  RESUME_NOT_FOUND = "RESUME_NOT_FOUND",
  UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE",
  FILE_TOO_LARGE = "FILE_TOO_LARGE",
  TEXT_EXTRACTION_FAILED = "TEXT_EXTRACTION_FAILED",
  INSUFFICIENT_EXTRACTED_TEXT = "INSUFFICIENT_EXTRACTED_TEXT",
  AI_PROVIDER_UNAVAILABLE = "AI_PROVIDER_UNAVAILABLE",
  AI_RATE_LIMITED = "AI_RATE_LIMITED",
  AI_TIMEOUT = "AI_TIMEOUT",
  STRUCTURED_OUTPUT_INVALID = "STRUCTURED_OUTPUT_INVALID",
  PARSED_DATA_VALIDATION_FAILED = "PARSED_DATA_VALIDATION_FAILED",
  PARSING_FAILED = "PARSING_FAILED",
}

