/**
 * Stable machine-readable reason codes for the Application Readiness Gate.
 * Controllers and workers must branch on these codes — never on free-form messages.
 */
export const READINESS_REASON_CODES = {
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  AUTO_APPLY_PAUSED: 'AUTO_APPLY_PAUSED',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  JOB_NOT_ACTIVE: 'JOB_NOT_ACTIVE',
  APPLY_URL_MISSING: 'APPLY_URL_MISSING',
  PROFILE_MISSING: 'PROFILE_MISSING',
  WORK_AUTHORIZATION_MISSING: 'WORK_AUTHORIZATION_MISSING',
  SPONSORSHIP_REQUIREMENT_MISSING: 'SPONSORSHIP_REQUIREMENT_MISSING',
  SPONSORSHIP_UNKNOWN_COMPATIBILITY: 'SPONSORSHIP_UNKNOWN_COMPATIBILITY',
  NOTICE_PERIOD_MISSING: 'NOTICE_PERIOD_MISSING',
  EXPERIENCE_MISSING: 'EXPERIENCE_MISSING',
  REMOTE_INCOMPATIBLE: 'REMOTE_INCOMPATIBLE',
  SALARY_INCOMPATIBLE: 'SALARY_INCOMPATIBLE',
  COMPANY_BLACKLISTED: 'COMPANY_BLACKLISTED',
  TITLE_EXCLUDED: 'TITLE_EXCLUDED',
  SOURCE_EXCLUDED: 'SOURCE_EXCLUDED',
  RELOCATION_PREFERENCE_MISSING: 'RELOCATION_PREFERENCE_MISSING',
  RESUME_MISSING: 'RESUME_MISSING',
  RESUME_INACTIVE: 'RESUME_INACTIVE',
  MATCH_SCORE_MISSING: 'MATCH_SCORE_MISSING',
  MATCH_SCORE_BELOW_THRESHOLD: 'MATCH_SCORE_BELOW_THRESHOLD',
  DAILY_LIMIT_REACHED: 'DAILY_LIMIT_REACHED',
  WEEKLY_LIMIT_REACHED: 'WEEKLY_LIMIT_REACHED',
  CONSENT_REQUIRED: 'CONSENT_REQUIRED',
  CHANNEL_UNSUPPORTED: 'CHANNEL_UNSUPPORTED',
  DUPLICATE_JOB_APPLICATION: 'DUPLICATE_JOB_APPLICATION',
  DUPLICATE_TRACKER_APPLICATION: 'DUPLICATE_TRACKER_APPLICATION',
  CONTACT_NAME_MISSING: 'CONTACT_NAME_MISSING',
  CONTACT_EMAIL_MISSING: 'CONTACT_EMAIL_MISSING',
  PORTFOLIO_NOT_PROVIDED: 'PORTFOLIO_NOT_PROVIDED',
  WORK_REGION_VERIFICATION_REQUIRED: 'WORK_REGION_VERIFICATION_REQUIRED',
  JOB_LOCATION_REQUIREMENT_NOT_MET: 'JOB_LOCATION_REQUIREMENT_NOT_MET',
  EXPERIENCE_REQUIREMENT_UNKNOWN: 'EXPERIENCE_REQUIREMENT_UNKNOWN',
  EXPERIENCE_REQUIREMENT_NOT_MET: 'EXPERIENCE_REQUIREMENT_NOT_MET',
  MOBILE_DESIGN_EVIDENCE_REQUIRED: 'MOBILE_DESIGN_EVIDENCE_REQUIRED',
  PORTFOLIO_EVIDENCE_REQUIRED: 'PORTFOLIO_EVIDENCE_REQUIRED',
  ANALYSIS_UNAVAILABLE: 'ANALYSIS_UNAVAILABLE',
  ANALYSIS_STALE: 'ANALYSIS_STALE',
  MATCH_CONSENT_REQUIRED: 'MATCH_CONSENT_REQUIRED',
  SPONSORSHIP_JOB_REQUIREMENT_NOT_MET: 'SPONSORSHIP_JOB_REQUIREMENT_NOT_MET',
} as const;

export type ReadinessReasonCode =
  (typeof READINESS_REASON_CODES)[keyof typeof READINESS_REASON_CODES];

/** Maps readiness decisions to worker failure codes (never transport failures). */
export const READINESS_WORKER_ERROR_CODES: Record<string, string> = {
  FEATURE_DISABLED: 'READINESS_FEATURE_DISABLED',
  INFORMATION_REQUIRED: 'READINESS_INFORMATION_REQUIRED',
  NOT_ELIGIBLE: 'READINESS_NOT_ELIGIBLE',
  LIMIT_REACHED: 'READINESS_LIMIT_REACHED',
  DUPLICATE: 'READINESS_DUPLICATE',
  CONSENT_REQUIRED: 'READINESS_CONSENT_REQUIRED',
  CHANNEL_UNSUPPORTED: 'READINESS_CHANNEL_UNSUPPORTED',
  JOB_UNAVAILABLE: 'READINESS_JOB_UNAVAILABLE',
};
