import type { SxProps, Theme } from '@mui/material/styles';

import { borderRadius, colorTokens, fontSize, fontWeight, shadows, spacing } from '@/tokens';

const compactBreakpoint = '@media (max-width: 47.5rem)';

export const aiMatchPageSx = {
  root: {
    display: 'grid',
    gap: spacing[5],
    width: '100%',

    [compactBreakpoint]: {
      gap: spacing[4],
    },
  },
  header: {
    alignItems: 'center',
    display: 'grid',
    gap: spacing[4],
    gridTemplateColumns: 'auto minmax(0, 1fr)',

    [compactBreakpoint]: {
      gap: spacing[3],
    },
  },
  headerIcon: {
    alignItems: 'center',
    background: colorTokens.actionPrimarySurface,
    borderRadius: borderRadius.xl,
    color: colorTokens.actionPrimary,
    display: 'grid',
    flexShrink: 0,
    height: spacing[12],
    justifyItems: 'center',
    width: spacing[12],
  },
  headerCopy: {
    display: 'grid',
    gap: spacing[1],
    minWidth: 0,
  },
  title: {
    color: colorTokens.textPrimary,
    fontSize: fontSize['2xl'],
    fontWeight: fontWeight.extraBold,
    lineHeight: 1.2,
    margin: 0,

    [compactBreakpoint]: {
      fontSize: fontSize.xl,
    },
  },
  subtitle: {
    color: colorTokens.textSecondary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
  },
  panel: {
    display: 'grid',
    gap: spacing[3],
    minWidth: 0,
  },
  composer: {
    background: colorTokens.backgroundCard,
    border: `0.0625rem solid ${colorTokens.borderSubtle}`,
    borderRadius: borderRadius.xl,
    boxShadow: shadows.card,
    display: 'grid',
    gap: spacing[3],
    justifyItems: 'stretch',
    padding: spacing[4],
    width: '100%',
  },
  composerHeader: {
    display: 'grid',
    gap: spacing[1],
  },
  composerTitle: {
    color: colorTokens.textPrimary,
    fontSize: fontSize.lg,
    fontWeight: fontWeight.extraBold,
    margin: 0,
  },
  composerDescription: {
    color: colorTokens.textSecondary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    margin: 0,
    maxWidth: '40rem',
  },
  composerActions: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing[2],
  },
  composerHint: {
    color: colorTokens.textSecondary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    margin: 0,
  },
  composerMeta: {
    color: colorTokens.textSecondary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    margin: 0,
  },
  groupSection: {
    background: colorTokens.backgroundCard,
    border: `0.0625rem solid ${colorTokens.borderSubtle}`,
    borderRadius: borderRadius.xl,
    boxShadow: shadows.card,
    display: 'grid',
    gap: spacing[3],
    padding: spacing[4],
  },
  groupHeader: {
    alignItems: 'baseline',
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing[1],
  },
  groupTitle: {
    color: colorTokens.textPrimary,
    fontSize: fontSize.base,
    fontWeight: fontWeight.extraBold,
    margin: 0,
  },
  groupMeta: {
    color: colorTokens.textSecondary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
  },
  selectField: {
    maxWidth: '26rem',
    width: '100%',
  },
  savedPanel: {
    background: colorTokens.backgroundCard,
    border: `0.0625rem solid ${colorTokens.borderSubtle}`,
    borderRadius: borderRadius.xl,
    boxShadow: shadows.card,
    display: 'grid',
    gap: spacing[4],
    padding: spacing[4],
    width: '100%',
  },
  savedToolbar: {
    alignItems: 'end',
    display: 'grid',
    gap: spacing[3],
    gridTemplateColumns: 'minmax(12rem, 18rem) minmax(0, 1fr) auto',

    [compactBreakpoint]: {
      alignItems: 'stretch',
      gridTemplateColumns: '1fr',
    },
  },
  savedToolbarCopy: {
    display: 'grid',
    gap: spacing[1],
    minWidth: 0,
    paddingBottom: spacing[1],
  },
  savedQueryChip: {
    color: colorTokens.textSecondary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    margin: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  savedToolbarActions: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing[2],
    justifyContent: 'flex-end',

    [compactBreakpoint]: {
      justifyContent: 'flex-start',
    },
  },
  savedDivider: {
    background: colorTokens.borderSubtle,
    border: 0,
    height: '0.0625rem',
    margin: 0,
    width: '100%',
  },
  savedCreateHeader: {
    display: 'grid',
    gap: spacing[1],
  },
  savedCreateTitle: {
    color: colorTokens.textPrimary,
    fontSize: fontSize.base,
    fontWeight: fontWeight.extraBold,
    margin: 0,
  },
  savedCreateRow: {
    alignItems: 'end',
    display: 'grid',
    gap: spacing[2],
    gridTemplateColumns: 'minmax(10rem, 14rem) minmax(0, 1fr) auto',
    width: '100%',

    [compactBreakpoint]: {
      alignItems: 'stretch',
      gridTemplateColumns: '1fr',
    },
  },
  banner: {
    alignItems: 'center',
    background: colorTokens.backgroundCard,
    border: `0.0625rem solid ${colorTokens.borderDefault}`,
    borderRadius: borderRadius.xl,
    boxShadow: shadows.card,
    display: 'grid',
    gap: spacing[3],
    gridTemplateColumns: 'auto minmax(0, 1fr) auto',
    padding: spacing[3],
    width: '100%',

    [compactBreakpoint]: {
      alignItems: 'start',
      gridTemplateColumns: 'auto minmax(0, 1fr)',
    },
  },
  bannerAction: {
    justifySelf: 'end',

    [compactBreakpoint]: {
      gridColumn: '1 / -1',
      justifySelf: 'start',
      width: '100%',
    },
  },
  bannerDanger: {
    borderColor: colorTokens.actionDanger,
  },
  bannerIcon: {
    alignItems: 'center',
    background: colorTokens.actionPrimarySurface,
    borderRadius: borderRadius.full,
    color: colorTokens.actionPrimary,
    display: 'grid',
    flexShrink: 0,
    height: spacing[10],
    justifyItems: 'center',
    width: spacing[10],
  },
  bannerIconDanger: {
    background: colorTokens.actionDangerSurface,
    color: colorTokens.actionDanger,
  },
  bannerCopy: {
    display: 'grid',
    gap: spacing[1],
    minWidth: 0,
  },
  bannerTitle: {
    color: colorTokens.textPrimary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    margin: 0,
  },
  bannerMessage: {
    color: colorTokens.textSecondary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    margin: 0,
  },
  empty: {
    alignItems: 'center',
    background: colorTokens.backgroundCard,
    border: `0.0625rem solid ${colorTokens.borderSubtle}`,
    borderRadius: borderRadius.xl,
    boxShadow: shadows.card,
    display: 'grid',
    gap: spacing[3],
    justifyItems: 'center',
    padding: `${spacing[8]} ${spacing[4]}`,
    textAlign: 'center',
  },
  emptyIcon: {
    alignItems: 'center',
    background: colorTokens.actionPrimarySurface,
    borderRadius: borderRadius.xl,
    color: colorTokens.actionPrimary,
    display: 'grid',
    height: spacing[12],
    justifyItems: 'center',
    width: spacing[12],
  },
  emptyTitle: {
    color: colorTokens.textPrimary,
    fontSize: fontSize.xl,
    fontWeight: fontWeight.extraBold,
    margin: 0,
  },
  emptyDescription: {
    color: colorTokens.textSecondary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    maxWidth: '28rem',
  },
  emptyActions: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing[2],
    justifyContent: 'center',
    marginTop: spacing[1],
  },
  listHeader: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing[2],
    justifyContent: 'space-between',
    minWidth: 0,
    width: '100%',

    [compactBreakpoint]: {
      alignItems: 'stretch',
      flexDirection: 'column',
      gap: spacing[2],
    },
  },
  resultCount: {
    color: colorTokens.textSecondary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
  },
  sortControl: {
    alignItems: 'center',
    display: 'flex',
    gap: spacing[2],
    minWidth: 0,

    [compactBreakpoint]: {
      alignItems: 'stretch',
      flexDirection: 'column',
      gap: spacing[1],
      width: '100%',
    },
  },
  sortLabel: {
    color: colorTokens.textSecondary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    whiteSpace: 'nowrap',
  },
  sortSelect: {
    minWidth: '10rem',

    [compactBreakpoint]: {
      minWidth: 0,
      width: '100%',
    },
  },
  savedTabPanel: {
    display: 'grid',
    gap: spacing[4],
    minWidth: 0,

    [compactBreakpoint]: {
      gap: spacing[3],
    },
  },
  savedJobsSection: {
    display: 'grid',
    gap: spacing[3],
    minWidth: 0,
    width: '100%',
  },
  textComposerCard: {
    background: colorTokens.backgroundCard,
    border: `0.0625rem solid ${colorTokens.borderSubtle}`,
    borderRadius: borderRadius.xl,
    boxShadow: shadows.card,
    display: 'grid',
    gap: spacing[3],
    padding: spacing[4],
    width: '100%',
  },
  careerComposerCard: {
    background: colorTokens.backgroundCard,
    border: `0.0625rem solid ${colorTokens.borderSubtle}`,
    borderRadius: borderRadius.xl,
    boxShadow: shadows.card,
    display: 'grid',
    gap: spacing[4],
    padding: spacing[4],
    width: '100%',

    [compactBreakpoint]: {
      gap: spacing[3],
      padding: spacing[3],
    },
  },
  textComposerFooter: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing[2],
    justifyContent: 'space-between',
  },
  textComposerActions: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing[2],
    marginLeft: 'auto',
  },
  charCount: {
    color: colorTokens.textTertiary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
  },
  dashedEmpty: {
    alignItems: 'center',
    background: colorTokens.backgroundCard,
    border: `0.125rem dashed ${colorTokens.borderSubtle}`,
    borderRadius: borderRadius.xl,
    display: 'grid',
    gap: spacing[3],
    justifyItems: 'center',
    padding: `${spacing[8]} ${spacing[4]}`,
    textAlign: 'center',
    width: '100%',
  },
  dashedEmptyArt: {
    alignItems: 'center',
    color: colorTokens.actionPrimary,
    display: 'grid',
    fontSize: '2.5rem',
    justifyItems: 'center',
    opacity: 0.85,
  },
  dashedEmptyTitle: {
    color: colorTokens.textPrimary,
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
    margin: 0,
    maxWidth: '28rem',
  },
  sectionTitle: {
    color: colorTokens.textPrimary,
    fontSize: fontSize.base,
    fontWeight: fontWeight.extraBold,
    margin: 0,
  },
  resumeFileCard: {
    alignItems: 'center',
    background: colorTokens.backgroundCard,
    border: `0.0625rem solid ${colorTokens.borderSubtle}`,
    borderRadius: borderRadius.xl,
    boxShadow: shadows.card,
    display: 'grid',
    gap: spacing[3],
    gridTemplateColumns: 'auto minmax(0, 1fr) auto',
    padding: spacing[3],
    width: '100%',

    [compactBreakpoint]: {
      gridTemplateColumns: 'auto minmax(0, 1fr)',
      '& > :last-child': {
        gridColumn: '1 / -1',
        justifySelf: 'start',
      },
    },
  },
  resumeFileIcon: {
    alignItems: 'center',
    background: colorTokens.actionDangerSurface,
    borderRadius: borderRadius.lg,
    color: colorTokens.actionDanger,
    display: 'grid',
    height: spacing[12],
    justifyItems: 'center',
    width: spacing[12],
  },
  resumeFileCopy: {
    display: 'grid',
    gap: spacing[1],
    minWidth: 0,
  },
  resumeFileName: {
    color: colorTokens.textPrimary,
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
    margin: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  resumeFileMeta: {
    color: colorTokens.textSecondary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    margin: 0,
  },
  resumeFileActions: {
    alignItems: 'center',
    display: 'flex',
    gap: spacing[1],
  },
  sourceJobCard: {
    alignItems: 'center',
    background: colorTokens.backgroundCard,
    border: `0.0625rem solid ${colorTokens.borderSubtle}`,
    borderRadius: borderRadius.xl,
    boxShadow: shadows.card,
    display: 'grid',
    gap: spacing[3],
    gridTemplateColumns: 'auto minmax(0, 1fr) auto',
    padding: spacing[3],
    width: '100%',

    [compactBreakpoint]: {
      gridTemplateColumns: 'auto minmax(0, 1fr)',
      '& > :last-child': {
        gridColumn: '1 / -1',
        justifySelf: 'start',
      },
    },
  },
  sourceJobLogo: {
    alignItems: 'center',
    background: colorTokens.backgroundApp,
    border: `0.0625rem solid ${colorTokens.borderSubtle}`,
    borderRadius: borderRadius.lg,
    color: colorTokens.textPrimary,
    display: 'grid',
    fontSize: fontSize.xl,
    fontWeight: fontWeight.extraBold,
    height: spacing[12],
    justifyItems: 'center',
    width: spacing[12],
  },
  sourceJobCopy: {
    display: 'grid',
    gap: spacing[1],
    minWidth: 0,
  },
  sourceJobLabel: {
    color: colorTokens.textTertiary,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    letterSpacing: '0.02em',
    margin: 0,
    textTransform: 'uppercase',
  },
  sourceJobTitle: {
    color: colorTokens.textPrimary,
    fontSize: fontSize.base,
    fontWeight: fontWeight.extraBold,
    margin: 0,
  },
  sourceJobMeta: {
    color: colorTokens.textSecondary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    margin: 0,
  },
  careerFormGrid: {
    display: 'grid',
    gap: spacing[3],
  },
  careerFormPreferences: {
    display: 'grid',
    gap: spacing[3],
    gridTemplateColumns: '1fr',

    '@media (min-width: 40rem)': {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },

    '@media (min-width: 64rem)': {
      gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    },
  },
  careerPathsSection: {
    borderTop: `0.0625rem solid ${colorTokens.borderSubtle}`,
    display: 'grid',
    gap: spacing[2],
    paddingTop: spacing[4],

    [compactBreakpoint]: {
      paddingTop: spacing[3],
    },
  },
  careerPathChips: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing[1],
  },
  careerPathChip: {
    background: colorTokens.backgroundApp,
    border: `0.0625rem solid ${colorTokens.borderSubtle}`,
    borderRadius: borderRadius.full,
    color: colorTokens.textSecondary,
    cursor: 'pointer',
    fontSize: fontSize.xs,
    fontWeight: fontWeight.medium,
    lineHeight: 1.35,
    padding: `${spacing[1]} ${spacing[2]}`,
    textAlign: 'left',
    transition: 'background-color 0.15s ease, border-color 0.15s ease, color 0.15s ease',

    '&:hover': {
      background: colorTokens.actionPrimarySurface,
      borderColor: colorTokens.actionPrimary,
      color: colorTokens.actionPrimary,
    },
  },
  careerPathChipActive: {
    background: colorTokens.actionPrimarySurface,
    borderColor: colorTokens.actionPrimary,
    color: colorTokens.actionPrimary,
  },
  careerPrivacy: {
    alignItems: 'center',
    color: colorTokens.textTertiary,
    display: 'flex',
    fontSize: fontSize.xs,
    fontWeight: fontWeight.medium,
    gap: spacing[1],
    justifyContent: 'center',
    textAlign: 'center',
    width: '100%',
  },
  careerComposerFooter: {
    alignItems: 'center',
    borderTop: `0.0625rem solid ${colorTokens.borderSubtle}`,
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing[2],
    justifyContent: 'flex-end',
    paddingTop: spacing[4],

    [compactBreakpoint]: {
      flexDirection: 'column',
      paddingTop: spacing[3],

      '& > *': {
        width: '100%',
      },
    },
  },
  savedChipsShell: {
    display: 'grid',
    gap: spacing[2],
    width: '100%',

    [compactBreakpoint]: {
      gap: spacing[1],
    },
  },
  savedChip: {
    alignItems: 'start',
    background: colorTokens.backgroundCard,
    border: `0.0625rem solid ${colorTokens.borderSubtle}`,
    borderRadius: borderRadius.xl,
    boxShadow: shadows.card,
    cursor: 'pointer',
    display: 'grid',
    flex: '0 0 auto',
    gap: spacing[1],
    minWidth: '10rem',
    padding: spacing[3],
    textAlign: 'left',
    transition: 'border-color 0.15s ease, background-color 0.15s ease',

    [compactBreakpoint]: {
      minWidth: '8.75rem',
      padding: spacing[2],
    },
  },
  savedChipIcon: {
    color: colorTokens.textTertiary,
    display: 'grid',
    justifyItems: 'start',
  },
  savedChipIconActive: {
    color: colorTokens.actionPrimary,
  },
  savedSearchActions: {
    alignItems: 'center',
    background: colorTokens.backgroundCard,
    border: `0.0625rem solid ${colorTokens.borderSubtle}`,
    borderRadius: borderRadius.xl,
    boxShadow: shadows.card,
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing[2],
    justifyContent: 'space-between',
    padding: spacing[3],
    width: '100%',
  },
  savedSearchActionsCopy: {
    display: 'grid',
    gap: spacing[1],
    minWidth: 0,
  },
  savedSearchActionsButtons: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing[2],
  },
  savedChipActive: {
    background: colorTokens.actionPrimarySurface,
    borderColor: colorTokens.actionPrimary,
  },
  savedChipNew: {
    alignContent: 'center',
    borderStyle: 'dashed',
    borderColor: colorTokens.actionPrimary,
    color: colorTokens.actionPrimary,
    justifyItems: 'center',
    minHeight: '4.5rem',
    textAlign: 'center',

    [compactBreakpoint]: {
      minHeight: '3.75rem',
    },
  },
  savedChipTitle: {
    color: colorTokens.textPrimary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    margin: 0,
  },
  savedChipMeta: {
    color: colorTokens.textSecondary,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.medium,
    margin: 0,
  },
  pagination: {
    alignItems: 'center',
    background: colorTokens.backgroundCard,
    border: `0.0625rem solid ${colorTokens.borderSubtle}`,
    borderRadius: borderRadius.xl,
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing[2],
    justifyContent: 'center',
    padding: `${spacing[2]} ${spacing[3]}`,
  },
  pageLabel: {
    color: colorTokens.textSecondary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    minWidth: '6rem',
    textAlign: 'center',
  },
} satisfies Record<string, SxProps<Theme>>;
