import type { FilterDropdownOption, JobCardData, JobFilter } from '@/components/molecules';

export const jobFilters: Omit<JobFilter, 'active'>[] = [
  { id: 'all', label: 'All Jobs' },
  { id: 'remote', label: 'Remote' },
  { id: 'full-time', label: 'Full Time' },
  { id: 'internship', label: 'Internship' },
  { id: 'hybrid', label: 'Hybrid' },
  { icon: 'ai', id: 'ai', label: 'AI Recommended' },
];

export const salaryOptions: FilterDropdownOption[] = [
  { label: 'All Salary', value: 'all' },
  { label: 'Under 15 LPA', value: 'under-15' },
  { label: '15 - 25 LPA', value: '15-25' },
  { label: '25+ LPA', value: '25-plus' },
];

export const experienceOptions: FilterDropdownOption[] = [
  { label: 'All Experience', value: 'all' },
  { label: '0 - 2 yrs', value: '0-2' },
  { label: '3 - 4 yrs', value: '3-4' },
  { label: '5+ yrs', value: '5-plus' },
];

export const jobs: JobCardData[] = [
  {
    accent: 'primary',
    company: 'Microsoft',
    experience: '5+ yrs',
    experienceBand: '5-plus',
    location: 'Bangalore, India',
    logo: 'M',
    postedAt: 'Posted 2d ago',
    salary: 'Rs 18 - 28 LPA',
    salaryBand: '25-plus',
    skills: ['React', 'TypeScript', 'Next.js', 'Azure', '+2'],
    tags: ['remote', 'ai'],
    title: 'Senior Frontend Engineer',
    type: 'Remote',
  },
  {
    accent: 'danger',
    company: 'Google',
    experience: '4+ yrs',
    experienceBand: '3-4',
    location: 'Bangalore, India',
    logo: 'G',
    postedAt: 'Posted 1d ago',
    salary: 'Rs 18 - 30 LPA',
    salaryBand: '25-plus',
    skills: ['React', 'TypeScript', 'Next.js', 'GraphQL', '+1'],
    tags: ['full-time', 'ai'],
    title: 'Senior Frontend Engineer',
    type: 'Full-time',
  },
  {
    accent: 'primary',
    company: 'Amazon',
    experience: '3+ yrs',
    experienceBand: '3-4',
    location: 'Bangalore, India',
    logo: 'a',
    postedAt: 'Posted 3d ago',
    salary: 'Rs 12 - 22 LPA',
    salaryBand: '15-25',
    skills: ['React', 'Node.js', 'Next.js', 'AWS', '+1'],
    tags: ['full-time'],
    title: 'Frontend Developer',
    type: 'Full-time',
  },
  {
    accent: 'danger',
    company: 'Adobe',
    experience: '2-4 yrs',
    experienceBand: '0-2',
    location: 'Noida, India',
    logo: 'A',
    postedAt: 'Posted 4d ago',
    salary: 'Rs 9 - 18 LPA',
    salaryBand: 'under-15',
    skills: ['React', 'TypeScript', 'UI/UX', 'Figma', '+1'],
    tags: ['hybrid'],
    title: 'Frontend Developer',
    type: 'Hybrid',
  },
  {
    accent: 'primary',
    company: 'Stripe',
    experience: '5+ yrs',
    experienceBand: '5-plus',
    location: 'Bengaluru, India',
    logo: 'S',
    postedAt: 'Posted 1d ago',
    salary: 'Rs 22 - 40 LPA',
    salaryBand: '25-plus',
    skills: ['React', 'Node.js', 'PostgreSQL', 'AWS', '+2'],
    tags: ['remote', 'ai'],
    title: 'Full Stack Developer',
    type: 'Remote',
  },
  {
    accent: 'danger',
    company: 'Airbnb',
    experience: '3-5 yrs',
    experienceBand: '3-4',
    location: 'Bangalore, India',
    logo: 'A',
    postedAt: 'Posted 5d ago',
    salary: 'Rs 16 - 26 LPA',
    salaryBand: '15-25',
    skills: ['React', 'TypeScript', 'Next.js', 'GraphQL', '+1'],
    tags: ['hybrid'],
    title: 'Frontend Engineer',
    type: 'Hybrid',
  },
  {
    accent: 'primary',
    company: 'Netflix',
    experience: '0-1 yrs',
    experienceBand: '0-2',
    location: 'Remote, India',
    logo: 'N',
    postedAt: 'Posted 6d ago',
    salary: 'Rs 6 - 10 LPA',
    salaryBand: 'under-15',
    skills: ['React', 'CSS', 'Testing', 'Git'],
    tags: ['internship', 'remote'],
    title: 'Frontend Intern',
    type: 'Internship',
  },
];
